site_name: Starlette
site_description: The little ASGI library that shines.

theme:
    name: 'material'

repo_name: encode/starlette
repo_url: https://github.com/encode/starlette
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Applications: 'applications.md'
    - Requests: 'requests.md'
    - Responses: 'responses.md'
    - WebSockets: 'websockets.md'
    - Routing: 'routing.md'
    - Endpoints: 'endpoints.md'
    - Middleware: 'middleware.md'
    - Static Files: 'staticfiles.md'
    - Events: 'events.md'
    - Background Tasks: 'background.md'
    - Exceptions: 'exceptions.md'
    - Debug: 'debug.md'
    - Test Client: 'testclient.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
