site_name: Starlette
site_description: The little ASGI library that shines.
site_url: https://www.starlette.io

theme:
  name: 'material'
  custom_dir: docs/overrides
  palette:
    - scheme: 'default'
      media: '(prefers-color-scheme: light)'
      toggle:
        icon: 'material/lightbulb'
        name: "Switch to dark mode"
    - scheme: 'slate'
      media: '(prefers-color-scheme: dark)'
      primary: 'blue'
      toggle:
        icon: 'material/lightbulb-outline'
        name: 'Switch to light mode'
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy

repo_name: encode/starlette
repo_url: https://github.com/encode/starlette
edit_uri: edit/master/docs/

nav:
  - Introduction: 'index.md'
  - Applications: 'applications.md'
  - Requests: 'requests.md'
  - Responses: 'responses.md'
  - WebSockets: 'websockets.md'
  - Routing: 'routing.md'
  - Endpoints: 'endpoints.md'
  - Middleware: 'middleware.md'
  - Static Files: 'staticfiles.md'
  - Templates: 'templates.md'
  - Database: 'database.md'
  - GraphQL: 'graphql.md'
  - Authentication: 'authentication.md'
  - API Schemas: 'schemas.md'
  - Lifespan: 'lifespan.md'
  - Background Tasks: 'background.md'
  - Server Push: 'server-push.md'
  - Exceptions: 'exceptions.md'
  - Configuration: 'config.md'
  - Test Client: 'testclient.md'
  - Sync Threadpools: 'threadpools.md'
  - Third Party Packages: 'third-party-packages.md'
  - Contributing: 'contributing.md'
  - Release Notes: 'release-notes.md'

markdown_extensions:
  - mkautodoc
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - 'js/chat.js'
  - 'js/sidecar-1.5.0.js'
